### ISSUE TITLE
Proposition de travailler sur une couche espaces d'occupation et de fonctionnement

### ISSUE THREAD

**Issue by bertandleroux** [cnigfr/zones-activites-economiques#2]
En complément d'une couche référentiel foncier économique, plusieurs observatoires distinguent certains espaces: bassin de rétention ou d'orage, route, zones de retournement...
intérêt à travailler sur une typologie codifiée de ces espaces.

**Comment by yoanndumon** [comment]
> En complément d'une couche référentiel foncier économique, plusieurs observatoires distinguent certains espaces: bassin de rétention ou d'orage, route, zones de retournement...
> 
> intérêt à travailler sur une typologie codifiée de ces espaces.

Oui pour ma part Cette approche est intéressante. 
En cas de mise en œuvre c'est une des dimensions pouvant décrire le foncier économique, mais attention l'occupation et l'usage fonctionnel peuvent couvrir pour beaucoup des notions bien différentes :

Occupation signifie-t-il qu'on souhaite décrire la couverture ou l'usage du foncier économique ? A ce moment le vocable "usage fonctionnel" me convient bien car il explicite de quoi on parle
Usage fonctionnel : bassin de rétention, routes, zones de retournement, espaces vert, autres équipements public, réseaux... mais alors comment les autres espaces : les espaces productifs ?

Si on parle d'occupation ne s'agit-il pas plutôt de décrire l'état d'occupation :
occupé, non occupé (jamais occupé), en voie d'occupation (chantier /travaux), partiellement vacant, totalement vacant ?

**Comment by yoanndumon** [comment]
Quelles sont les classes proposées par urbansimul ?

**Comment by bertandleroux** [comment]
code | libellé
-- | --
1 | Route
2 | Bassin d'orage,   bassin de rétention
3 | Parkings,   stationnement
4 | Zone de retournement   P.L
5 | Espaces Verts
6 | Zones de service
7 | Autre espace   indisponible
8 | Espace disponible
9 | Occupation en   transition
10 | Carrières, zones   d'extraction
NULL | Non Connu

**Comment by yoanndumon** [comment]
Les classes 7 et 8 proposées dans urban simul me perturbent car on est sur une notion de disponibilité plutôt que de fonctionnalités 

Espace disponible : je comprends tout espace non encore affecté aux fonctions de production secondaire ou tertiaire 

Espace non disponible : je comprends tout espace déjà affecté aux fonctions de production secondaire ou tertiaire
