### ISSUE TITLE
terr_maitrise attribut de : TERRAIN-ECO

### ISSUE THREAD

**Issue by yoanndumon** [cnigfr/zones-activites-economiques#26]
Après consultation du comité technique du GT ZAE régional le type énuméré **terr_maitrise** attribut de **TERRAIN-ECO** apparait pas tout à fait satisfaisant, y'a t-il moyen de faire figurer ou distinguer dans le type de maîtrise foncière les EPCI (c'est quand même eux qui ont la compétence au titre de la loi NOTRE), ainsi que les SEM et les Etablissements Publics Foncier ?

**Comment by GT-CNIG-DDU** [comment]
Discussion à poursuivre dans #4
