### ISSUE TITLE
terr_usage - attribut de : TERRAIN-ECO

### ISSUE THREAD

**Issue by yoanndumon** [cnigfr/zones-activites-economiques#29]
terr_usage - attribut de : TERRAIN-ECO
Après consultation du comité technique de notre GT ZAE régional, il vous est proposé les compléments ou alternatives aux libellés des type énumérés suivants :

- voirie
- parkings, stationnement
- zone de retournement poids lourds
- autres équipements publics
- **infrastructures**
- bâti à vocation économique
- bâti à vocation résidentiel
- bassin d'orage ou de rétention
- **espace vert / espace d'agrément**
- **espace naturel et forestier**
- espace agricole
- carrières, zones d'extraction
- dépôt, stockage
- (zone de service ?)

Quelqu'un peut-il définir ce qu'on entend par "zone de service"

Veuillez noter que pour des terrains occupé par des bâtiments la plupart du temps il s'agira de bâti à vocation économique, cependant il peut exister une sorte de désaffectation de certaines zones ancienne par la conquête du résidentiel aussi il faut prévoir "bâti à vocation résidentiel"

**Comment by GT-CNIG-DDU** [comment]
Discussion à poursuivre dans #18
