### ISSUE TITLE
Intérêt à travailler sur une couche référentiel foncier économique

### ISSUE THREAD

**Issue by bertandleroux** [cnigfr/zones-activites-economiques#3]
Selon les territoires, l'unité spatiale d'analyse peut différer : parcelle, unités foncières, lots commercialisés ou anticipation de division parcellaire.

intérêt à avoir une couche d'information de suivi du foncier qui permette de s'adapter à la finalité principale d'observation et aux capacités et ambitions de mise à jour du suivi du foncier.

**Comment by haubourg** [comment]
Assez d'accord. Je préférerais que les TUP soient un référentiel externe d'analyse, et que les ZAE soient des agrégations parcelles cadastrales. La notion de propriété étant tellement variante dans le temps (plus que les parcelles), on risque d'avoir du mal à créer des contours proches de la réalités. 
Les TUP sont en revanche une très bonne aide à la saisie ou à la construction en masse des ZAE. Mais j'imposerais pas la TUP comme unité élémentaire personnellement

**Comment by GT-CNIG-DDU** [comment]
Le [sous-groupe ZAE du 17 mai](https://cnig.gouv.fr/IMG/pdf/230524_cr_sg_zae_gt_amenagement_cnig_230517.pdf) a décidé de considérer la notion de terrain à vocation économique, cf. classe `TERRAIN-ECO`  dans le [projet de standard](https://github.com/cnigfr/zones-activites-economiques/tree/main/standard).

Le terrain à vocation économique peut anticiper un remembrement cadastral. Il s'appuie globalement sur la limite de parcelle cadastrale mais peut également la subdiviser.
