### ISSUE TITLE
Intérêt de catégoriser le type de maîtrise foncière sur un référentiel foncier économique

### ISSUE THREAD

**Issue by yoanndumon** [cnigfr/zones-activites-economiques#4]
Type de maîtrise foncière :
PP personne physique (anonymisé)
PM privée personne morale de droit privée 
PM public personne morale de droit public

**Comment by Doctor-Who** [comment]
Ne pourrait on pas reprendre la typologie des fichiers fonciers ? 
Cf : http://doc-datafoncier.cerema.fr/ff/doc_fftp/variable/pnb10_parcelle/catpropro2

**Comment by yoanndumon** [comment]
Dans la version la moins détaillée peut-être (colonne observation)

**Comment by yoanndumon** [comment]
Après consultation du comité technique du GT ZAE régional le type énuméré **terr_maitrise** attribut de **TERRAIN-ECO** apparait pas tout à fait satisfaisant, est-il possible de faire figurer ou distinguer dans le type de maîtrise foncière les EPCI (c'est quand même eux qui ont la compétence au titre de la loi NOTRE), les SEM et les Etablissement publics foncier ?

**Comment by GT-CNIG-DDU** [comment]
Le [SG ZAE du 11/07/2023](https://cnig.gouv.fr/IMG/pdf/230713_cr_sg_zae_gt_amenagement_cnig_230711.pdf) a adopté cette proposition. La liste de valeurs "terr_maitrise_fonc" est augmentée des valeurs détaillées des rubriques "P – État et collectivité territoriale" et "F –Professionnel du foncier et immobilier" (cf. libellés de la colonne "valeur " de [catpropro2](http://doc-datafoncier.cerema.fr/ff/doc_fftp/variable/pnb10_parcelle/catpropro2) pour les rubriques P et F).
