### ISSUE TITLE
Attributs dates sur zae

### ISSUE THREAD

**Issue by yoanndumon** [cnigfr/zones-activites-economiques#5]
(1) S'agit-il de la date de création de l'enregistrement dans la base de données ?
ou bien
(2) S'agit-il de la date de création de la ZAE par l'EPCI ?

si (2) il parait contraignant que la valeur soit obligatoire car je crains dans beaucoup de cas que cette date ne soit pas connue ou du moins mettre l'année

Peut-on expliciter l'usage de date d'identification ?

**Comment by guillaumecastella** [comment]
Je souscris au fait de rendre la date de création de la ZAE facultative car nous aurons du mal a trouver cette information. Nous avons déjà certaines fois du mal à déterminer la limite exacte entre 2 ZAE contiguës, donc pour la date...
J'avoue également ne pas trop comprendre ce qui se cache derrière la "date d'identification".
Enfin, il me paraît important de conserver le caractère obligatoire de la date de dernière modification des informations de la ZAE.

**Comment by Doctor-Who** [comment]
> (1) S'agit-il de la date de création de l'enregistrement dans la base de données ? ou bien (2) S'agit-il de la date de création de la ZAE par l'EPCI ?

Je comprends ` zae_creation_date` comme la date de création de la zone.
Si seulement l'année est connue, il faudrait se mettre d'accord sur une convention type 2015-00-00 (les 00 indique que le jour et mois ne sont pas connus) 
Je vous suis tous les deux sur le caractère facultatif de cette information et pouvoir indiquer 0000-00-00 si inconnu.

`zae_identif_date` serait la date "d'apparition" dans la base de données du standard ? 

Dans ce cas, il manque la date de mise à jour de l'emprise et des informations de la zone. C'est traité sur l'emprise foncière via `emp_actu_date` mais pas sur ce niveau. Ne faudrait il pas ajouter `zae_actu_date` ?

**Comment by GT-CNIG-DDU** [comment]
> Je comprends ` zae_creation_date` comme la date de création de la zone.

exact

> il faudrait se mettre d'accord sur une convention type 2015-00-00 (les 00 indique que le jour et mois ne sont pas connus)

Cette convention n'est pas autorisée par ISO 8601 et encore moins par les outils de saisie de date. Plutôt 2015-01-01 ? (avec une mention comme valeur conventionnelle pour les millésimes)


> Je vous suis tous les deux sur le caractère facultatif de cette information

Ok et j'en prends note pour le projet de standard : "valeur vide autorisée"


> Ne faudrait il pas ajouter `zae_actu_date`

L'attribut est bien présent

**Comment by Doctor-Who** [comment]
> Cette convention n'est pas autorisée par ISO 8601 et encore moins par les outils de saisie de date. Plutôt 2015-01-01 ? (avec une mention comme valeur conventionnelle pour les millésimes)

Merci pour cette information.
Ok pour 2015-01-01.

> L'attribut est bien présent

Effectivement, je l'avais manqué, c'est parfait donc.

**Comment by yoanndumon** [comment]
Pourquoi pas année de création de la zone d'activités ? Plutôt qu'une date qu'on aura pas de façon systématique.
Il ne faut pas contraindre à ce que ce champ soit obligatoire la plupart du temps nous n'en disposons pas.

Avoir date création de l'enregistrement dans la base de donnés et date de mise à jour de l'enregistrement en obligatoire oui.

**Comment by GT-CNIG-DDU** [comment]
Le [projet de standard](https://github.com/cnigfr/zones-activites-economiques/tree/main/standard) a été modifié en conséquence.
- année de création de la zone d'activités (au lieu de la date précise) : valeur vide autorisée
- site_identif_date (date d'identification du site économique) et site_actu_date (date de dernière actualisation des informations sur le site économique) : valeurs obligatoires.
