### ISSUE TITLE
Page 9 contexte réglementaire

### ISSUE THREAD

**Issue by yoanndumon** [cnigfr/zones-activites-economiques#7]
On ne parle pas de la loi NOTRe ?

**Comment by VerandaB** [comment]
> La mention à la Loi NOTRe est désormais intégrée au [projet de standard](https://github.com/cnigfr/zones-activites-economiques/tree/main/standard), au §2 Contexte réglementaire.

Je viens de consulter la version du 9 juin. Il pourrait être judicieux de développer la mention de la Loi NOTRe, en explicitant que les intercommunalités possèdent désormais la compétence développement économique et que, en conséquence, le transfert des ZAE aux intercos est prévu.
Cela permet de lever l'éventuelle ambiguïté qui pourrai apparaître à la fin du paragraphe "Loi Climat et Résilience", toujours à la page 9. "L'inventaire est établi sur son territoire **par l'autorité compétente**"

**Comment by VerandaB** [comment]
> La mention à la Loi NOTRe est désormais intégrée au [projet de standard](https://github.com/cnigfr/zones-activites-economiques/tree/main/standard), au §2 Contexte réglementaire.

Je viens de consulter la version du 9 juin. Il pourrait être judicieux de développer la mention de la Loi NOTRe, en explicitant que les intercommunalités possèdent désormais la compétence développement économique et que, en conséquence, le transfert des ZAE aux intercos est prévu.
Cela permet de lever l'éventuelle ambiguïté qui pourrai apparaître à la fin du paragraphe "Loi Climat et Résilience", toujours à la page 9. "L'inventaire est établi sur son territoire **par l'autorité compétente**"

**Comment by GT-CNIG-DDU** [comment]
@VerandaB, proposition : 

La loi n°2015-991 du 7 août 2015 portant nouvelle organisation territoriale de la République (NOTRe) renforce les compétences des communautés de communes et d’agglomération. Elle a organisé le transfert obligatoire de l'ensemble des ZAE aux EPCI à compter du 1er janvier 2017 avec un pouvoir de gestion étendu.
