### ISSUE TITLE
ZAE.v ou ZAE.vocaxxx booléen ?

### ISSUE THREAD

**Issue by yoanndumon** [cnigfr/zones-activites-economiques#8]
Vocation dominante ou plusieurs vocations booléen ?

**Comment by guillaumecastella** [comment]
Même si nous allions vers un système basé sur plusieurs vocations en booléen, est-ce que pour autant nous n'aurions pas besoin de conserver une notion de vocation dominante ?
Si oui, comment la déterminer ?

**Comment by yoanndumon** [comment]
Vocation constatée ou vocation souhaitée ou vocation déclarée ?

Vocation principale ou vocations présentes ?

Je pense qu'il faut rester sur l'effectif pour déterminer la vocation majoritaire. 
Le faire en nombre d'établissements ne fonctionnera pas.

Si la vocation se détermine en fonction du nombre d'emplois majoritaires quelle nomenclature pour passer des code APE des établissements vers les grandes catégories artisanales commerciales industrielles etc...
Quels seuils ? Classe d'effectifs majoritaires ? 
Encore faut-il avoir les effectifs des établissements concernés ? Le fichiers SIRENE ne comporte que des tranches. 

Enfin rendre ce champ facultatif car une ZAE sans occupant n'aurait alors pas de vocation déterminée.

**Comment by GT-CNIG-DDU** [comment]
Attribut `site_vocadomi` conservé dans le [projet de standard](https://github.com/cnigfr/zones-activites-economiques/tree/main/standard), défini en première approche comme "Vocation dominante _constatée_ du site économique".

**Comment by GT-CNIG-DDU** [comment]
Intégration dans le [projet de standard](https://github.com/cnigfr/zones-activites-economiques/tree/main/standard) des 7 attributs `site_voca_<voc>` comme _attributs optionnels_ booléens avec valeur vide autorisée. 

\<voc\> prenant les valeurs :  industrielle, commerciale, tertiaire, artisanale, touristique, portuaire, aéroportuaire

Attribut | Définition | Type | Contraintes
-- | -- | -- | --
site_vocadomi | vocation dominante constatée du site économique (liste de valeurs site_vocadomi) | varchar | valeur obligatoire
... | -- | -- | --
_site_voca_industrielle_ | le site comprend (oui / non) au moins une activité industrielle | booléen | valeur vide autorisée
_site_voca_commerciale_ | le site comprend (oui / non) au moins une activité commerciale | booléen | valeur vide autorisée
etc.  |  | booléen | valeur vide autorisée
